controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

#api_list:
#    path: /load
#    controller: App\Controller\PosApisController::load
    # if the action is implemented as the __invoke() method of the
    # controller class, you can skip the '::method_name' part:
    # controller: App\Controller\BlogController